### PR TITLE
Use attribute 'temporarilyOffline' instead 'offline' for enabling/disabling nodes.

### PR DESCRIPTION
**Pull request by manox**
Using the 'offline' attribute to decide whether to toggle the state of nodes on activation/deactivation results in incorrect behavior. If a previously activated node is offline, e.g. because there is no connection, and you use the noce enable function, it will be actually deactivated. The attribute 'temporarilyOffline' must be used instead.

Also see https://github.com/pbelskiy/ujenkins/pull/9.

### CODE REVIEW

**Comment by pbelskiy** [comment]
> Using the 'offline' attribute to decide whether to toggle the state of nodes on activation/deactivation results in incorrect behavior. If a previously activated node is offline, e.g. because there is no connection, and you use the noce enable function, it will be actually deactivated. The attribute 'temporarilyOffline' must be used instead.
> 
> Also see [pbelskiy/ujenkins#9](https://github.com/pbelskiy/ujenkins/pull/9).

Thanks for PR. What about `jenkinsapi` approach? 
To prevent this they raise an exception, when node online but disconnected.

https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/node.py (207 line)

I suggest to do the same, and also add new function to `nodes` module, like `launch_agent`.

So you can do something like that in your case:
```python
import asyncio
import aiojenkins

jenkins = aiojenkins.Jenkins('http://your_server/jenkins', 'user', 'password')

async def main():
    try:
        await jenkins.nodes.enable('some_node')
    except aiojenkins.JenkinsNodeError:
        print('Seems like node disconnected, `offline` is True, but `temporarilyOffline` is False')
        await jenkins.nodes.launch_agent('some_node')

asyncio.run(main())
```

What do you think? And what disadvantages of this?

**Comment by pbelskiy** [comment]
There is some problem with coveralls and PRs, I gotta fix it firstly.

**Comment by manox** [comment]
I think if the attribute "temporarilyOffline" is false and a previously disrupted connection to the agent is re-established, the agent will start on its own.

Also with the jenkinsapi method, you have no way to disable nodes that are not currently connected.

**Comment by pbelskiy** [comment]
@manox Hello! Could you rebase please? I've probably fixed coveralls problem on PRs

**Comment by pbelskiy** [comment]
So there are three states of a node:
```
1) disconnected (`offline` is True and `temporarilyOffline` is False)
2) enabled (`temporarilyOffline` is True)
3) disabled  (`temporarilyOffline` is False)
```

---

On node **enable()**
```
  1) disconnected -> skip or raise NodeError?
  2) enabled -> skip
  3) disabled -> enable
```

On node **disable()**
```
  1) disconnected -> skip or raise NodeError? 
  2) enabled -> disable node
  3) disabled -> pass
```

@manox what do you think about disconnected node state behaviour on call enable or disable?

**Comment by manox** [comment]
With the described division of the states, they are not unique. I think about the states differently. In my way of thinking there are the following 3 states: 

```
1) online (`offline` is False and `temporarilyOffline` is False)
2) offline (`offline` is True and `temporarilyOffline` is False)
3) disabled (`temporarilyOffline` is True)
```

**Comment by pbelskiy** [comment]
For example official Java client of Jenkins are so poor, and has only toggle method.
https://github.com/jenkinsci/java-client-api/blob/master/jenkins-client/src/main/java/com/offbytwo/jenkins/model/ComputerWithDetails.java

**Pull request merged**
