### PR TITLE
Add unit sec to delay parameter

### PR DESCRIPTION
**Pull request by kkpattern**
The delay parameter requires a "sec" unit to function correctly.

I also added a test for this.

### CODE REVIEW

**Comment by pbelskiy** [comment]
@kkpattern Hello! Thanks or your PR. But when Jenkins starts to require it? 

Could you please share some information about this?

**Comment by kkpattern** [comment]
> @kkpattern Hello! Thanks or your PR. But when Jenkins starts to require it?
> 
> Could you please share some information about this?

Sorry I don’t know since when Jenkins starts to require it. We have added the sec unit since 2019 in jenkinsapi. You can easily reproduce this by removing the sec unit and run the newly added test. The build will be triggered immediately instead of waiting for two seconds.

**Comment by pbelskiy** [comment]
@kkpattern thanks! I will check it later

**Review by pbelskiy — APPROVED** [review]

**Comment by pbelskiy** [comment]
@kkpattern thanks. also you could create PR for https://github.com/pbelskiy/ujenkins if you want!

PS: using f-string is preferrable

**Comment by kkpattern** [comment]
> @kkpattern thanks. also you could create PR for https://github.com/pbelskiy/ujenkins if you want!
> 
> PS: using f-string is preferrable

Happy to create PR for ujenkins. I didn't use f-string in aiojenkins because I remembered aiojenkins still supports python3.5 right? I will use f-string in ujenkins.

**Comment by pbelskiy** [comment]
@kkpattern actually support of Python 3.5 and 3.6 was dropped half year ago.

**Pull request merged**
